# Generated by Django 4.2.14 on 2024-07-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=models.CharField(max_length=32), max_length=32),
        ),
    ]
