# Generated by Django 4.2.14 on 2024-07-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0002_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32),
        ),
    ]
