# Generated by Django 4.2.14 on 2024-07-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
