# Generated by Django 4.2.14 on 2024-07-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Female'), (2, 'Male')])),
                ('age', models.DecimalField(decimal_places=1, max_digits=5)),
                ('status', models.BooleanField(default=False)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petplanet.breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petplanet.user')),
            ],
        ),
    ]
