# Generated by Django 4.2.14 on 2024-07-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0009_alter_dog_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.AddField(
            model_name='dog',
            name='age_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dog',
            name='age_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='avatar',
            field=models.ImageField(blank=True, default='dogAvatars/default.png', upload_to='dogAvatars/'),
        ),
    ]
