# Generated by Django 4.2.14 on 2024-07-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0010_remove_dog_age_dog_age_month_dog_age_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='dogAvatars/'),
        ),
    ]
