# Generated by Django 4.2.14 on 2024-07-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0011_alter_dog_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='avatar',
            field=models.ImageField(blank=True, default='dogAvatars/default.png', upload_to='dogAvatars/'),
        ),
    ]
