# Generated by Django 4.2.14 on 2024-07-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0017_post_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
