# Generated by Django 4.2.14 on 2024-07-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0020_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='has_image',
        ),
        migrations.AddField(
            model_name='party',
            name='dogs',
            field=models.ManyToManyField(related_name='parties', to='petplanet.dog'),
        ),
    ]
