# Generated by Django 4.2.14 on 2024-07-31 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0022_alter_image_image_partyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='party',
            name='dog_limit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='hold_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
