# Generated by Django 4.2.14 on 2024-08-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0025_party_hold_at_time_alter_party_hold_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_accept', models.BooleanField(blank=True, default=True)),
                ('result', models.TextField()),
                ('dogs', models.ManyToManyField(blank=True, related_name='application', to='petplanet.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petplanet.user')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petplanet.party')),
            ],
        ),
    ]
