# Generated by Django 4.2.14 on 2024-08-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0026_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_accept',
            field=models.BooleanField(blank=True),
        ),
    ]
