# Generated by Django 4.2.14 on 2024-08-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petplanet', '0029_alter_application_is_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='party_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='party_author', to='petplanet.user'),
            preserve_default=False,
        ),
    ]
